export THEOS = /Users/az/theos
BUNDLE_NAME = ReynardDefaultPrefs

ReynardDefaultPrefs_FILES = RDRootVC.m
ReynardDefaultPrefs_CFLAGS = -fobjc-arc
ReynardDefaultPrefs_FRAMEWORKS = UIKit
ReynardDefaultPrefs_PRIVATE_FRAMEWORKS = Preferences
ReynardDefaultPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
