BUNDLE_NAME = ReynardDefaultCC

ReynardDefaultCC_FILES = ReynardDefaultCC.m
ReynardDefaultCC_CFLAGS = -fobjc-arc
ReynardDefaultCC_INSTALL_PATH = /Library/ControlCenter/Bundles
ReynardDefaultCC_BUNDLE_EXTENSION = bundle
ReynardDefaultCC_PRIVATE_FRAMEWORKS = ControlCenterUIKit

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
